Collection View
Marchenkos/CollectionViewTask pull request #1
Opened 2022-03-15 11:14 UTC by Marchenkos

2022-03-16 11:54 UTC, KirillMikhailovich requested changes

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/Layout/CollectionMosaicCell.swift
> +    static let identifer = "CollectionMosaicCellIdentifer"
По неймингу в идеале давать более точные названия. cellId или что-то такое. У лучше все же запихивать в Constants

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/Layout/CollectionMosaicLayout.swift
> +    }
Это функция где-то используется?

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/Layout/CollectionMosaicLayout.swift
> +}
А эта?)

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/Utils/NavigationTransition.swift
> +    var animationDuraction = 1.4
Duraction -> Duration

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/Utils/NavigationTransition.swift
> +    var animationDuraction = 1.4
И лучше Constants

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/Utils/NavigationTransition.swift
> +            toView.transform = CGAffineTransform(scaleX: 0.001, y: 0.001)
Constants

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/View/CollectionViewController.swift
> +    @IBOutlet var collectionView: UICollectionView!
Лучше не делать force unwrap

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/View/CollectionViewController.swift
> +
Поаккуратнее с пробелами)

2022-03-16 11:54 UTC, KirillMikhailovich commented on Podfile
> +  pod 'SwiftLint'
У тебя линтер не ругается?

<img width="263" alt="Снимок экрана 2022-03-16 в 14 49 36" src="https://user-images.githubusercontent.com/23502271/158583709-384b2ba9-d352-43db-8eba-2036ec457746.png">

2022-03-16 11:54 UTC, KirillMikhailovich commented on CollectionViewTask/Utils/NavigationTransition.swift
> +            let presentedViewCenter = toView.center
Выглядит так, что они стартуют не из центра

https://user-images.githubusercontent.com/23502271/158583899-97f3662c-449a-4b0d-85c9-a0cef3ff85d3.mp4

2022-03-17 08:53 UTC, Marchenkos commented on CollectionViewTask/Layout/CollectionMosaicLayout.swift
> +    }
да, layoutAttributesForItem переопрределена здесь и возващает кэшированные атрибуты для каждого айтема

2022-03-17 08:54 UTC, Marchenkos commented on CollectionViewTask/Layout/CollectionMosaicLayout.swift
> +}
Эта тоже используется, но возващает атрибуты для всех ячеек, без нее контент не отображается

2022-03-17 12:26 UTC, KirillMikhailovich approved these changes

2023-05-10 06:56 UTC, merged